# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66825d2f6a001fbea4db5f21fd39485aef2871816bb77c149227c4b08f404bbcd8cf11beb0d6119f309bb5ec501952863f2dccc1f17d1a1748a3681cc071ad09

test:
  secret_key_base: 52ac71fc8ec4f645bd109e0cef2098e58693da2d159e4092c3dee1b7db847722b997aabb090788a537b092ef318a2191233fca3aa3da9b258f95d184e7f35b4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
